### PR TITLE
The cheese balls are invading the Battle Ready and Michael is awaiting your response

### PR DESCRIPTION
**Pull request by valkyrienyanko**

### CODE REVIEW

**Comment by lunaradev1** [comment]
It seems like this **Optimizes the code** from what I am seeing, is that correct?

**Comment by valkyrienyanko** [comment]
Batman approves

**Comment by lunaradev1** [comment]
All right, code seems safe. Merging it!

**Comment by valkyrienyanko** [comment]
https://github.com/Yoshiboi18303/Godot-Installer/assets/6277739/37cdabef-be34-4140-aca8-c0ed886e0982

**Comment by valkyrienyanko** [comment]
The code is the same speed before or after this commit. I only made your code more readable imo.

**Pull request merged**
